### ISSUE TITLE
Schema Feedback

### ISSUE THREAD

**Issue by edherm** [D-Tanner/DinoFlow#1]
Hello DinoFlow team!

I have reviewed your schema and wanted to leave you some comments. Please look these over, discuss them with your team, and feel free to ask me any questions that you may have.

- [ ] Please make a graphical representation of your schema as well. I find it's really helpful when it comes to visualizing your database's relationships. [This is a diagramming tool that I like.](https://dbdiagram.io/home)

## `Questions` Table
- [ ] This table should have an user/stegAuthorSaurusId (I could't help myself) column to connect a question to it's writer.
- [ ] Up/downvotes for 'Questions' should be a bonus feature and will involve a polymorphic relationship. We can talk about this toward the end of next week if y'all are ready for bonuses.
## `Answers` Table
- [ ] This table also needs a foreign key to connect it to an author.
- [ ] Up/downvotes should be it's own table.
## Votes for Questions Table
- [ ] Move `up` and `down` columns to this table from your `answers` table.
- [ ] Change the foreign key from `questionId` to `answerId`.

**Comment by jh9374** [comment]
Please review updated [schema](https://github.com/appacademy-starters/express-project-planning-example/wiki/Database-Schema)

**Comment by edherm** [comment]
Thanks for your changes, y'all. It all looks good to me.
